# -*- coding: utf-8 -*-
"""md to sqlite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hv3KO_p-c-ZTlD9_3arFa7OWD1_Za0OJ
"""

"""
DPR Extraction MD → SQLite Converter
======================================
Colab-ready script. Handles:
  - One initial document MD  (full doc map + all components)
  - Multiple component-level MDs  (one per component extraction run)
  - All go into a single SQLite database

HOW TO USE:
  1. Run all cells.
  2. A file picker will appear automatically.
  3. Select ALL your .md extraction files at once (Ctrl/Cmd + click).
  4. Wait — knowledge.db will be created in /content/.
  5. Download knowledge.db from the Colab sidebar (Files panel).
"""

# ─────────────────────────────────────────────────────────────────────────────
# Cell 1 — Imports
# ─────────────────────────────────────────────────────────────────────────────
import re
import json
import sqlite3
import hashlib
import os
import glob
import sys
from datetime import datetime, timezone
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Cell 2 — Config  (edit these)
# ─────────────────────────────────────────────────────────────────────────────

DB_PATH  = "knowledge.db"   # output SQLite file
MD_GLOB  = "*.md"           # default glob when using run()
RESET_DB = False            # True = wipe DB on each run (testing only)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 3 — Colab upload helpers
# ─────────────────────────────────────────────────────────────────────────────

def upload_and_run(db_path: str = DB_PATH, reset: bool = RESET_DB):
    """
    Show a Colab file-upload widget.
    Select ALL your .md files at once — initial doc + all component files.
    They are saved to /content/ and processed into a single SQLite database.
    """
    try:
        from google.colab import files as colab_files
    except ImportError:
        print("Not running in Colab — use run() with a file list or glob instead.")
        return

    print("─" * 60)
    print("Select your .md extraction files")
    print("Hold Ctrl (Windows/Linux) or Cmd (Mac) to select multiple files")
    print("─" * 60)
    uploaded = colab_files.upload()

    if not uploaded:
        print("No files uploaded.")
        return

    saved_paths = []
    for fname, content in uploaded.items():
        dest = f"/content/{fname}"
        Path(dest).write_bytes(content)
        saved_paths.append(dest)
        print(f"  Uploaded: {fname}  ({len(content):,} bytes)")

    print()
    run(file_list=saved_paths, db_path=db_path, reset=reset)

    # Offer download of the database
    print(f"\nDownload your database:")
    colab_files.download(db_path)



def extract_json_blocks(md_text: str) -> list[dict]:
    """Pull every ```json ... ``` block out of markdown text."""
    pattern = re.compile(r'```json\s*(.*?)\s*```', re.DOTALL)
    blocks = []
    for match in pattern.finditer(md_text):
        try:
            obj = json.loads(match.group(1))
            blocks.append(obj)
        except json.JSONDecodeError as e:
            print(f"  ⚠ JSON parse error (skipping block): {e}")
    return blocks


def split_blocks(blocks: list[dict]) -> tuple[dict | None, list[dict]]:
    """
    Separate one SchemaManifest from ExtractionResult blocks.
    Returns (manifest_or_None, [extraction_results])
    """
    manifest = None
    extractions = []
    for b in blocks:
        if b.get("type") == "SchemaManifest":
            manifest = b
        elif b.get("should_extract") is True and b.get("rows") is not None:
            extractions.append(b)
    return manifest, extractions


def safe_table_name(name: str) -> str:
    """Ensure table name is safe SQL — lowercase, underscores, no reserved words."""
    SQL_RESERVED = {
        "order", "group", "select", "where", "table", "index",
        "values", "insert", "update", "delete", "create", "drop",
        "from", "join", "set", "by", "as", "is", "in", "on",
        "not", "and", "or", "null"
    }
    safe = re.sub(r'[^a-z0-9_]', '_', name.lower())[:60]
    safe = re.sub(r'_+', '_', safe).strip('_')
    if safe in SQL_RESERVED:
        safe = f"tbl_{safe}"
    return safe


def safe_col_name(name: str) -> str:
    """Ensure column name is safe SQL."""
    SQL_COL_RESERVED = {"type", "id", "name", "value", "index", "order", "group"}
    safe = re.sub(r'[^a-z0-9_]', '_', name.lower())
    if safe in SQL_COL_RESERVED:
        safe = f"col_{safe}"
    return safe


def ddl_col_fragment(col: dict) -> str:
    """Build a single column definition string for CREATE TABLE."""
    name = safe_col_name(col["name"])
    sql_type = col.get("sql_type", "TEXT")

    # Compliance columns must always be TEXT — guard against bool/INTEGER mistake
    if "compliance" in name and sql_type == "INTEGER":
        sql_type = "TEXT"

    # Requirement text columns must always be nullable — source docs routinely
    # have blank requirement cells (e.g. DCS.011–DCS.021 in core switch tables)
    NULLABLE_ALWAYS = {
        "minimum_requirement", "min_requirement",
        "minimum_required_specifications", "minimum_requirement_description",
        "minimum_required_description",
    }
    if name in NULLABLE_ALWAYS:
        nullable = True
    else:
        nullable = col.get("nullable", True)

    parts = [f'"{name}" {sql_type}']
    if not nullable:
        parts.append("NOT NULL")
    if col.get("is_primary_key", False):
        parts.append("PRIMARY KEY")
    return " ".join(parts)


def build_create_table(table_name: str, manifest_entry: dict, rows: list | None = None) -> str:
    """
    Generate CREATE TABLE IF NOT EXISTS DDL from a SchemaManifest entry.
    Always appends lineage columns + auto-increment _row_id if no PK defined.

    rows: if provided, used to verify is_primary_key at the data level —
          overrides manifest if duplicates or nulls are detected.
    """
    safe_name = safe_table_name(table_name)
    ddl_cols = manifest_entry.get("ddl_columns", [])

    # Runtime PK safety check: verify claimed PKs against actual row data
    if rows:
        for col in ddl_cols:
            if col.get("is_primary_key", False):
                field = col["name"]
                values = [r.get(field) for r in rows]
                has_null = any(v is None or v == "N/A" for v in values)
                has_dup  = len(set(str(v) for v in values if v is not None)) < len([v for v in values if v is not None])
                if has_null or has_dup:
                    col = dict(col)  # don't mutate original
                    col["is_primary_key"] = False
                    ddl_cols = [c if c["name"] != field else col for c in ddl_cols]

    has_pk = any(c.get("is_primary_key", False) for c in ddl_cols)

    col_defs = []

    # Auto-increment PK when source has no unique key
    if not has_pk:
        col_defs.append('"_row_id" INTEGER PRIMARY KEY AUTOINCREMENT')

    for col in ddl_cols:
        col_defs.append(ddl_col_fragment(col))

    # Fixed lineage columns
    fixed_lineage = [
        {"name": "_section_path",    "sql_type": "TEXT"},
        {"name": "_parent_component","sql_type": "TEXT"},
        {"name": "_source_row_count","sql_type": "INTEGER"},
        {"name": "_extracted_at",    "sql_type": "TEXT"},
        {"name": "_source_file",     "sql_type": "TEXT"},
    ]
    seen = {safe_col_name(c["name"]) for c in ddl_cols}
    for col in fixed_lineage:
        cname = safe_col_name(col["name"])
        if cname not in seen:
            col_defs.append(f'"{cname}" {col["sql_type"]}')

    return (
        f'CREATE TABLE IF NOT EXISTS "{safe_name}" (\n'
        + ',\n'.join(f'    {c}' for c in col_defs)
        + '\n)'
    )


def ensure_columns(conn: sqlite3.Connection, table_name: str, row_keys: list[str]):
    """
    ALTER TABLE to add any columns present in row data but missing from table.
    Prevents insert failures when a new .md file has extra fields.
    """
    safe_name = safe_table_name(table_name)
    cursor = conn.execute(f'PRAGMA table_info("{safe_name}")')
    existing = {row[1].lower() for row in cursor.fetchall()}

    for key in row_keys:
        safe_key = safe_col_name(key)
        if safe_key not in existing:
            conn.execute(f'ALTER TABLE "{safe_name}" ADD COLUMN "{safe_key}" TEXT')
            print(f"    ALTER TABLE {safe_name}: added column {safe_key}")


def insert_rows(
    conn: sqlite3.Connection,
    table_name: str,
    rows: list[dict],
    section_path: str,
    parent_component: str,
    source_row_count: int,
    source_file: str,
):
    """
    Idempotent bulk insert.
    Delete existing rows for this (source_file, section_path) before inserting.
    """
    safe_name = safe_table_name(table_name)
    now = datetime.now(timezone.utc).isoformat()

    # Idempotent: remove previous rows from this exact section + file
    conn.execute(
        f'DELETE FROM "{safe_name}" WHERE _source_file = ? AND _section_path = ?',
        (source_file, section_path)
    )

    if not rows:
        return 0

    # Ensure all columns in rows exist in the table
    all_keys = set()
    for row in rows:
        all_keys.update(row.keys())
    ensure_columns(conn, table_name, list(all_keys))

    inserted = 0
    for row in rows:
        # Build insert dict with safe column names + lineage
        safe_row = {safe_col_name(k): v for k, v in row.items()}
        safe_row["_section_path"]     = section_path
        safe_row["_parent_component"] = parent_component
        safe_row["_source_row_count"] = source_row_count
        safe_row["_extracted_at"]     = now
        safe_row["_source_file"]      = source_file

        cols = ', '.join(f'"{k}"' for k in safe_row)
        placeholders = ', '.join('?' for _ in safe_row)
        values = list(safe_row.values())

        try:
            conn.execute(
                f'INSERT INTO "{safe_name}" ({cols}) VALUES ({placeholders})',
                values
            )
            inserted += 1
        except sqlite3.IntegrityError as e:
            # PRIMARY KEY violation — shouldn't happen after is_primary_key fixes
            # but handle gracefully: insert without PK column
            print(f"    ⚠ IntegrityError on {safe_name}: {e} — skipping row")

    return inserted


def create_registry_table(conn: sqlite3.Connection):
    """
    _extraction_registry tracks every .md file processed and its manifest.
    Useful for debugging and the downstream DPR builder.
    """
    conn.execute("""
        CREATE TABLE IF NOT EXISTS _extraction_registry (
            registry_id      TEXT PRIMARY KEY,
            source_file      TEXT NOT NULL,
            document_name    TEXT,
            table_name       TEXT NOT NULL,
            physical_table   TEXT NOT NULL,
            schema_version   INTEGER,
            content_type     TEXT,
            section_path     TEXT,
            parent_component TEXT,
            row_count        INTEGER,
            processed_at     TEXT NOT NULL
        )
    """)

    # _document_index: one row per .md file, classifies initial vs component
    conn.execute("""
        CREATE TABLE IF NOT EXISTS _document_index (
            file_id          TEXT PRIMARY KEY,
            source_file      TEXT NOT NULL UNIQUE,
            document_name    TEXT,
            file_type        TEXT NOT NULL,   -- 'initial' | 'component' | 'unknown'
            component_name   TEXT,            -- e.g. "Component 2: CCTV"
            tables_created   INTEGER DEFAULT 0,
            sections_loaded  INTEGER DEFAULT 0,
            rows_inserted    INTEGER DEFAULT 0,
            processed_at     TEXT NOT NULL
        )
    """)


def detect_file_type(md_text: str, extractions: list[dict]) -> tuple[str, str | None]:
    """
    Classify a .md file as 'initial' (full document) or 'component' (single component).
    Returns (file_type, component_name_or_None).

    Heuristics:
      - If all extractions share the same parent_component → component-level file
      - If extractions span multiple parent_components → initial/full document
      - If no extractions (DocumentMap only) → initial
    """
    if not extractions:
        return "initial", None

    parents = {ex.get("parent_component", "") for ex in extractions if ex.get("parent_component")}

    if len(parents) == 1:
        return "component", parents.pop()
    elif len(parents) > 1:
        return "initial", None
    else:
        return "unknown", None


def upsert_document_index(
    conn: sqlite3.Connection,
    source_file: str,
    doc_name: str | None,
    file_type: str,
    component_name: str | None,
    result: dict,
):
    file_id = hashlib.sha256(source_file.encode()).hexdigest()[:16]
    conn.execute("""
        INSERT OR REPLACE INTO _document_index
        (file_id, source_file, document_name, file_type, component_name,
         tables_created, sections_loaded, rows_inserted, processed_at)
        VALUES (?,?,?,?,?,?,?,?,?)
    """, (
        file_id,
        source_file,
        doc_name,
        file_type,
        component_name,
        result.get("tables", 0),
        result.get("sections", 0),
        result.get("rows", 0),
        datetime.now(timezone.utc).isoformat(),
    ))


def upsert_registry(
    conn: sqlite3.Connection,
    source_file: str,
    doc_name: str | None,
    entry: dict,
    row_count: int,
):
    registry_id = hashlib.sha256(
        f"{source_file}:{entry.get('section_path','')}:{entry.get('table_name','')}".encode()
    ).hexdigest()[:16]

    conn.execute("""
        INSERT OR REPLACE INTO _extraction_registry
        (registry_id, source_file, document_name, table_name, physical_table,
         schema_version, content_type, section_path, parent_component,
         row_count, processed_at)
        VALUES (?,?,?,?,?,?,?,?,?,?,?)
    """, (
        registry_id,
        source_file,
        doc_name,
        entry.get("table_name", ""),
        safe_table_name(entry.get("table_name", "")),
        entry.get("schema_version", 1),
        entry.get("content_type", ""),
        entry.get("section_path", ""),
        entry.get("parent_component", ""),
        row_count,
        datetime.now(timezone.utc).isoformat(),
    ))


# ── Cell 5: Main converter ────────────────────────────────────────────────────

def process_md_file(
    md_path: str,
    conn: sqlite3.Connection,
) -> dict:
    """
    Process a single .md file:
      1. Parse all JSON blocks
      2. Use SchemaManifest to CREATE TABLEs
      3. Use ExtractionResult blocks to INSERT rows
    Returns a summary dict.
    """
    source_file = Path(md_path).name
    print(f"\n{'='*60}")
    print(f"Processing: {source_file}")
    print(f"{'='*60}")

    text = Path(md_path).read_text(encoding="utf-8")
    blocks = extract_json_blocks(text)
    manifest, extractions = split_blocks(blocks)

    print(f"  JSON blocks found: {len(blocks)}")
    print(f"  Manifest: {'✓' if manifest else '✗ (missing — will infer from ExtractionResults)'}")
    print(f"  Extraction blocks: {len(extractions)}")

    doc_name = manifest.get("document_name") if manifest else None

    # Detect file type (initial full doc vs component-level)
    file_type, component_name = detect_file_type(text, extractions)
    if file_type == "component":
        print(f"  File type: component  [{component_name}]")
    elif file_type == "initial":
        print(f"  File type: initial (full document / multi-component)")
    else:
        print(f"  File type: unknown")

    # ── Step 1: CREATE TABLES from SchemaManifest ──────────────────────────
    tables_created = 0
    if manifest:
        # Verify total_tables count
        declared = manifest.get("total_tables", len(manifest.get("tables", [])))
        actual   = len(manifest.get("tables", []))
        if declared != actual:
            print(f"  ⚠ SchemaManifest total_tables={declared} but tables array has {actual} — using array")

        for entry in manifest.get("tables", []):
            tname = entry.get("table_name", "")
            if not tname:
                continue
            # Find rows for this table to enable runtime PK verification
            ex_for_table = next(
                (e for e in extractions if e.get("table_name") == tname), {}
            )
            table_rows = ex_for_table.get("rows") or []
            ddl = build_create_table(tname, entry, rows=table_rows)
            try:
                conn.execute(ddl)
                tables_created += 1
                print(f"  ✓ Table ready: {safe_table_name(tname)}")
            except sqlite3.OperationalError as e:
                print(f"  ⚠ Could not create {tname}: {e}")
    else:
        # No manifest — infer table schemas from ExtractionResult fields
        print("  ℹ No SchemaManifest — inferring schemas from ExtractionResult fields")
        for ex in extractions:
            tname = ex.get("table_name", "")
            if not tname:
                continue
            # Build a synthetic manifest entry from fields[]
            ddl_cols = []
            for f in (ex.get("fields") or []):
                ddl_cols.append({
                    "name":           f.get("name", ""),
                    "sql_type":       f.get("sql_type", "TEXT"),
                    "nullable":       f.get("nullable", True),
                    "is_primary_key": f.get("is_primary_key", False),
                })
            synthetic_entry = {
                "table_name":     tname,
                "ddl_columns":    ddl_cols,
                "lineage_columns": [],
            }
            table_rows = ex.get("rows") or []
            ddl = build_create_table(tname, synthetic_entry, rows=table_rows)
            try:
                conn.execute(ddl)
                tables_created += 1
                print(f"  ✓ Table ready (inferred): {safe_table_name(tname)}")
            except sqlite3.OperationalError as e:
                print(f"  ⚠ Could not create {tname}: {e}")

    # ── Step 2: INSERT rows from ExtractionResult blocks ──────────────────
    total_rows = 0
    for ex in extractions:
        tname    = ex.get("table_name", "")
        rows     = ex.get("rows") or []
        sec_path = ex.get("section_path", "")
        parent   = ex.get("parent_component", "")
        src_rows = ex.get("source_row_count", len(rows))

        if not tname or not rows:
            continue

        n = insert_rows(conn, tname, rows, sec_path, parent, src_rows, source_file)
        total_rows += n
        print(f"  ✓ Inserted {n:>4} rows → {safe_table_name(tname)}")

        # Update registry
        manifest_entry = {}
        if manifest:
            manifest_entry = next(
                (t for t in manifest.get("tables", []) if t.get("table_name") == tname),
                {}
            )
        manifest_entry["section_path"]     = sec_path
        manifest_entry["parent_component"] = parent
        manifest_entry["schema_version"]   = ex.get("schema_version", 1)
        manifest_entry["content_type"]     = ex.get("content_type", "")
        manifest_entry["table_name"]       = tname
        upsert_registry(conn, source_file, doc_name, manifest_entry, n)

    conn.commit()
    result = {"tables": tables_created, "sections": len(extractions), "rows": total_rows}
    print(f"\n  Summary: {tables_created} tables | {len(extractions)} sections | {total_rows} rows")

    # Register this file in the document index
    upsert_document_index(conn, source_file, doc_name, file_type, component_name, result)
    conn.commit()

    result["file_type"]      = file_type
    result["component_name"] = component_name
    return result


# ─────────────────────────────────────────────────────────────────────────────
# Cell 6 — Main run function
# ─────────────────────────────────────────────────────────────────────────────

def run(
    md_glob: str = MD_GLOB,
    file_list: list[str] | None = None,
    db_path: str = DB_PATH,
    reset: bool = RESET_DB,
):
    """
    Process .md extraction files into a single SQLite database.

    Args:
        md_glob:   Glob pattern for .md files (used if file_list is None)
        file_list: Explicit list of file paths (used by upload_and_run)
        db_path:   Output SQLite database path
        reset:     If True, delete the DB before running (testing only)

    Examples:
        run()                              # all *.md in working dir
        run("noida_*.md")                  # specific glob
        run(file_list=["c1.md","c2.md"])   # explicit list
        run(reset=True)                    # wipe and rebuild
    """
    # Resolve file list
    if file_list is not None:
        md_files = sorted(str(p) for p in file_list)
    else:
        md_files = sorted(glob.glob(md_glob))

    if not md_files:
        src = "file_list" if file_list is not None else f"glob '{md_glob}'"
        print(f"No .md files found from {src}.")
        print("Upload your extraction .md files and re-run.")
        return

    print(f"Files to process: {len(md_files)}")
    for f in md_files:
        print(f"  {Path(f).name}")

    if reset and os.path.exists(db_path):
        os.remove(db_path)
        print(f"\nReset: removed existing {db_path}")

    conn = sqlite3.connect(db_path)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    create_registry_table(conn)
    conn.commit()

    totals = {"files": 0, "tables": 0, "sections": 0, "rows": 0}
    file_results = []

    for md_path in md_files:
        result = process_md_file(md_path, conn)
        totals["files"]    += 1
        totals["tables"]   += result["tables"]
        totals["sections"] += result["sections"]
        totals["rows"]     += result["rows"]
        file_results.append((Path(md_path).name, result))

    conn.close()

    # ── Final summary ─────────────────────────────────────────────────────
    print(f"\n{'='*60}")
    print("DONE")
    print(f"  Files processed : {totals['files']}")
    print(f"  Tables created  : {totals['tables']}")
    print(f"  Sections loaded : {totals['sections']}")
    print(f"  Rows inserted   : {totals['rows']}")
    print(f"  Database        : {os.path.abspath(db_path)}")

    # Per-file breakdown
    print(f"\nPer-file breakdown:")
    for fname, r in file_results:
        ftype = r.get("file_type", "unknown")
        comp  = r.get("component_name") or ""
        label = f"[{ftype}] {comp}" if comp else f"[{ftype}]"
        print(f"  {fname:<40} {label:<45} {r['sections']:>3} sections  {r['rows']:>5} rows")

    # Table inventory
    conn = sqlite3.connect(db_path)
    print(f"\n{'─'*60}")
    print("Tables in database:")
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
    ).fetchall()
    system_tables = {"_extraction_registry", "_document_index", "sqlite_sequence"}
    data_tables   = [(r[0],) for r in rows if r[0] not in system_tables]
    system_only   = [(r[0],) for r in rows if r[0] in system_tables]

    for (name,) in data_tables:
        count = conn.execute(f'SELECT COUNT(*) FROM "{name}"').fetchone()[0]
        print(f"  {name:<60} {count:>6} rows")

    print(f"\nSystem tables:")
    for (name,) in system_only:
        count = conn.execute(f'SELECT COUNT(*) FROM "{name}"').fetchone()[0]
        print(f"  {name:<60} {count:>6} rows")

    # Document index
    print(f"\nDocument index (_document_index):")
    idx_rows = conn.execute(
        "SELECT source_file, file_type, component_name, tables_created, rows_inserted FROM _document_index ORDER BY file_type, source_file"
    ).fetchall()
    for r in idx_rows:
        comp = r[2] or ""
        print(f"  [{r[1]:<10}] {r[0]:<35} {comp:<40} {r[3]} tables  {r[4]} rows")

    conn.close()
    print(f"{'='*60}")


# ─────────────────────────────────────────────────────────────────────────────
# Entry point — runs automatically when you execute this script in Colab
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    upload_and_run()